### ISSUE TITLE
compose() 변경

### ISSUE THREAD

**Issue by pueue** [pueue/game-of-gene#5]
1. 인자를 나중에 받을 수 있도록 변경. 이름그대로 함수를 합성하는 역할로만 변경하고 실행은 유보.

```js
// from
const result = compose(1, a=>a+1, a=>a*2);

// to
const add1AndDouble = compose(a=>a+1, a=>a*2);
const result = add1AndDouble(1);
```

2. 수학에서의 [함수의 합성](https://ko.wikipedia.org/wiki/%ED%95%A8%EC%88%98%EC%9D%98_%ED%95%A9%EC%84%B1)과 일치하는 표기법으로 변경. 오른쪽부터 함수를 실행.

**Comment by khw1031** [comment]
음 왼쪽에서 부터 합성하는걸로 하면 안되나? 함수 실행 순서를 다시 한 번 생각해야 돼서

**Comment by pueue** [comment]
그럼 1번만 적용하고 compose 순서는 그대로 두자. 나도 오른쪽방향이 편해

compose 별칭으로 pipe도 두면 좋을듯
